name: ZAP Scanner
on:
  workflow_run:
    workflows: ["Deploy Dev"]
    types:
      - completed

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the application
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report'
          target: '${{ secrets.DEV_ROUTE }}'
